### ISSUE TITLE
connecting to wrong sts endpoint https://sts..amazonaws.com

### ISSUE THREAD

**Issue by Sampathreddygopireddy118** [qonto/prometheus-rds-exporter#100]
**Describe the bug**
I'm using your helm chart and I have passed the assume role `PROMETHEUS_RDS_EXPORTER_AWS_ASSUME_ROLE_ARN: arn:aws:iam::00000000:role/rds-exporter` and I see it is trying to get the GetCallerIdentity it is trying with wrong sts end point. below is the log

{"time":"2023-12-27T18:17:04.653877227Z","level":"DEBUG","msg":"Assume role","role":"arn:aws:iam::00000000:role/rds-exporter"}
{"time":"2023-12-27T18:17:04.653954968Z","level":"DEBUG","msg":"search AWS region using IMDS"}
{"time":"2023-12-27T18:17:04.656602818Z","level":"INFO","msg":"found AWS region via IMDS","region":"us-east-1"}
{"time":"2023-12-27T18:17:04.658949862Z","level":"ERROR","msg":"can't identify AWS account and/or region","reason":"can't fetch information about current session: operation error STS: GetCallerIdentity, get identity: get credentials: failed to refresh cached credentials, operation error STS: AssumeRole, https response error StatusCode: 0, RequestID: , request send failed, Post \"https://sts..amazonaws.com/\": dial tcp: lookup sts..amazonaws.com: no such host"}

wrong sts end point
**Desktop (please complete the following information):**

 - OS: [e.g. Linux]
 - Prometheus RDS exporter's version [e.g. 1.1]
 - RDS engine: [e.g. PostgreSQL]

**To Reproduce**
add env parametes as below in the vaules.yaml
env: 
  PROMETHEUS_RDS_EXPORTER_DEBUG: "true"
  PROMETHEUS_RDS_EXPORTER_AWS_ASSUME_ROLE_ARN: arn:aws:iam::00000000:role/rds-exporter
  PROMETHEUS_RDS_EXPORTER_AWS_ASSUME_ROLE_SESSION: "rds-exporter"
Steps to reproduce the behavior

**Expected behavior**

It has to connect to https://sts.amazonaws.com
**Additional context**
sts endpoint has 2 dots (..)

**Comment by vmercierfr** [comment]
Hello,

There is a problem finding the correct address for the AWS STS service. It should be sts.**us-east-1**.amazonaws.com (or `sts.amazonaws.com` in legacy environment).

It could be related to the AWS authentication method used. I'd be happy to help you solve this deployment problem.

Can you share more context about your deployment:

- What version of the RDS exporter do you use?
- Are you using AWS EKS?
- What authentication method are you using (IRSA, AWS IAM credentials via AWS environment variables, AWS IAM credentials in a file, SSO, ...)?

And test the following steps: 

1. Check that the AWS credentials used in the Kubernetes pod are correct
2. Set `AWS_DEFAULT_REGION` and `AWS_REGION`

Thanks,

**Comment by vmercierfr** [comment]
Hello @Sampathreddygopireddy118,

Do you still have an issue with STS? If yes, can you apply suggestions from [my previous message](https://github.com/qonto/prometheus-rds-exporter/issues/100#issuecomment-1874277801). If there is no update, I will close the issue by the end of the week to avoid outdated issues.

Thanks,

**Comment by bryanfang** [comment]
the issue will also occur when fetch metrics from AWS China, since the domain name for AWS China is amazonaws.com.cn rather then amazonaws.com

**Comment by vmercierfr** [comment]
The AWS SDK should use amazonaws.com.cn domain automatically. To make it work you need to set `AWS_DEFAULT_REGION` and `AWS_REGION` environment variables and  the role ARN should use [aws-cn partition](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html#arns-syntax) like `arn:aws-cn:iam::00000000:role/rds-exporter`

Do you still have the issue with these parameters?

**Comment by qfritz** [comment]
Closing this request as it looks like it has been resolved with last comment.
