### ISSUE TITLE
The dashboard display is abnormal

### ISSUE THREAD

**Issue by xucq07** [qonto/prometheus-rds-exporter#168]
I don’t know why, but there are metric data in Prometheus, yet the dashboard doesn’t display the data.
Please tell me why.

![1714456856193](https://github.com/qonto/prometheus-rds-exporter/assets/99275967/adf4b7e3-6d1c-41e4-a50f-2c3f64c647f5)

![1714458860532](https://github.com/qonto/prometheus-rds-exporter/assets/99275967/74dd613a-7eaa-4242-8056-1dac95e74d10)

**Comment by qfritz** [comment]
Hi there, just a small question to be sure, if you use "View" on one of the empty visualisation, does it show any value?
