### ISSUE TITLE
Allow restriction of running instance to specific cluster or clusters

### ISSUE THREAD

**Issue by jstewart612** [qonto/prometheus-rds-exporter#169]
### Is your feature request related to a problem? Please describe

The all-or-none approach of this exporter is a SPOF.  I tend to like to avoid those in my environment.

### Describe the solution you'd like

As such, I would like the ability to lock down a running copy of the exporter to only gather information on specific cluster or clusters.

### Describe alternatives you've considered

I have worked around this problem with metricRelabelings in the helm chart.  I would like to stop having to do this and putting splat operators in my IAM policies.

### Additional context

None required.

**Comment by vmercierfr** [comment]
Thanks for reporting your usage, I agree that is required feature.

If you don't mind, I'll close this issue in favor of https://github.com/qonto/prometheus-rds-exporter/issues/94, which is similar.
