### ISSUE TITLE
Support for monitoring RDS in different account within same organization

### ISSUE THREAD

**Issue by kdvermagojoko** [qonto/prometheus-rds-exporter#201]
### Is your feature request related to a problem? Please describe

I am able to monitor RDS in same account where my EKS cluster is present with prometheus-rds-exporter-chart. I am trying to look for configuration to monitor RDS running in different account in same organization. Is it supported?

### Describe the solution you'd like

I should be able to monitor other accounts RDS using this chart by providing correct role, policy and assume role configuration. 

### Describe alternatives you've considered

Other way is to install these chart in all accounts and then monitor from there.

### Additional context

NA

**Comment by qfritz** [comment]
Hello please find here [my previous answer for this topic](https://github.com/qonto/prometheus-rds-exporter/issues/194#issuecomment-2202169655). The similar issue #130 will be used to follow developments.
