### ISSUE TITLE
Unable to deploy the exporter

### ISSUE THREAD

**Issue by anamika-nih** [qonto/prometheus-rds-exporter#229]
### Describe the bug

I used the following command from the readme documentation. 

```
helm upgrade \
prometheus-rds-exporter \
oci://public.ecr.aws/qonto/prometheus-rds-exporter-chart \
--version ${PROMETHEUS_RDS_EXPORTER_VERSION} \
--install \
--namespace ${KUBERNETES_NAMESPACE} \
--set serviceAccount.annotations."eks\.amazonaws\.com\/role-arn"="${SERVICE_ACCOUNT_ANNOTATION}" \
--values values.yaml
```
Following is the error:
`Release "prometheus-rds-exporter" does not exist. Installing it now.
Pulled: public.ecr.aws/qonto/prometheus-rds-exporter-chart:0.10.1
Digest: sha256:4f4941e00ba920c0de88acb6d9ee1f0d8bb3ed9e6f4b16e0859954831c3e5717
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "prometheus-rds-exporter-prometheus-rds-exporter-chart" namespace: "" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first`
### Desktop (please complete the following information)

- OS: EKS
- Prometheus RDS exporter's version 0.10.1
- RDS engine: [e.g. PostgreSQL]

Could you please tell me what is wrong?

### To Reproduce

Steps to reproduce the behavior

**Comment by qfritz** [comment]
Hi there, is there a [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) deployed in your cluster? 

If no, please try installing it first and retry RDS exporter deployment 🙇‍♀️

**Comment by anamika-nih** [comment]
Hi @qfritz thanks for your reply. Do both prometheus and rds exporter have to be in the same namespace?

**Comment by anamika-nih** [comment]
I was able to deploy both successfully, thank you
