### ISSUE TITLE
The metrics are not loading up on the dashboard

### ISSUE THREAD

**Issue by anamika-nih** [qonto/prometheus-rds-exporter#230]
### Describe the bug

I was able to successfully deploy the exporter, and on checking the logs I am able to see that the metrics are being scraped by the rds-exporter
```
{"time":"2024-11-05T21:37:44.41068891Z","level":"DEBUG","msg":"received query"}
{"time":"2024-11-05T21:37:44.410739091Z","level":"INFO","msg":"get RDS metrics"}
{"time":"2024-11-05T21:37:44.410768362Z","level":"DEBUG","msg":"fetch quotas"}
{"time":"2024-11-05T21:37:44.410850425Z","level":"DEBUG","msg":"fetch usage metrics"}
{"time":"2024-11-05T21:37:44.456071149Z","level":"DEBUG","msg":"usage metrics fetched","metrics":{"AllocatedStorage":128849018880,"DBInstances":25,"ManualSnapshots":50,"ReservedDBInstances":0}}
{"time":"2024-11-05T21:37:50.300046315Z","level":"DEBUG","msg":"RDS metrics fetched"}
{"time":"2024-11-05T21:37:50.300102397Z","level":"DEBUG","msg":"fetch cloudwatch metrics"}
{"time":"2024-11-05T21:37:50.300123897Z","level":"DEBUG","msg":"fetch EC2 metrics"}
{"time":"2024-11-05T21:37:50.3337287Z","level":"DEBUG","msg":"EC2 metrics fetched","metrics":{"Instances":{"db.m5.large":{"BaselineIOPS":3600,"BaselineThroughput":85196800,"MaximumIops":18750,"MaximumThroughput":622592000,"Memory":8589934592,"Vcpu":2},"db.m6i.large":{"BaselineIOPS":3600,"BaselineThroughput":85196800,"MaximumIops":40000,"MaximumThroughput":1310720000,"Memory":8589934592,"Vcpu":2},"db.r6g.xlarge":{"BaselineIOPS":6000,"BaselineThroughput":155713536,"MaximumIops":20000,"MaximumThroughput":622592000,"Memory":34359738368,"Vcpu":4},"db.t3.micro":{"BaselineIOPS":500,"BaselineThroughput":11403264,"MaximumIops":11800,"MaximumThroughput":273285120,"Memory":1073741824,"Vcpu":2}}}}
```

However, the metrics are not visible on the dashboard.
Could you please help with the troubleshooting steps? 

![image](https://github.com/user-attachments/assets/3484ca45-8ea7-4872-ba7e-924e0fe05e06)

### Desktop (please complete the following information)

- OS: AWS EKS
- Prometheus RDS exporter's version 0.10.1
- RDS engine: [e.g. PostgreSQL]

### To Reproduce

Steps to reproduce the behavior

**Comment by qfritz** [comment]
Hi, to make metrics visible in this dashboard, you need to select all filters like

```
Datasource, AWS account, Region, Instance
```

If the filters aren't available check if a random metric (like `rds_allocated_storage_bytes`) is visible in the prometheus UI. If it's not the case, something my be wrong and prometheus might not be scrapping your configuration.

**Comment by anamika-nih** [comment]
The other options like AWS account, Region, Instance are not loading up. Does prometheus and the exporter have to be in the same namespace?

**Comment by anamika-nih** [comment]
Actually, the scrape.yml was not configured with the new target. I can see the metrics now, thank you :)
