### ISSUE TITLE
Enhancement - allow the ability to set priorityclassname within the helmchart

### ISSUE THREAD

**Issue by cjwong1098** [qonto/prometheus-rds-exporter#26]
within the helm chart (configs/helm/templates/deployment.yaml) can the ability of setting "priorityclassname" name be exposed?

https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

thanks!

**Comment by vmercierfr** [comment]
Hello,

We just released the [v0.3.0](https://github.com/qonto/prometheus-rds-exporter/releases/tag/0.3.0) that contains the [priorityClassName](https://github.com/qonto/prometheus-rds-exporter/blob/main/configs/helm/values.yaml#L37) Helm chart parameter to configure it.

Please upgrade to this version to have the option.
