### ISSUE TITLE
Add RDS tags

### ISSUE THREAD

**Issue by NikitaGl** [qonto/prometheus-rds-exporter#37]
**Is your feature request related to a problem? Please describe.**

Current implementation suggest to fetch data about rds instances across all account/region, which is already great, but lacks additional precision. We have around 50+ databases per region and use tags to be able filter them based on specific tag value.

**Describe the solution you'd like**

An ability to collect info about instance tags and add them as metric labels would increase possibilities of filtering data we collect.

**Comment by vmercierfr** [comment]
In our initial use case, we needed to collect metrics from all RDS instances, but it makes sense to support instance filtering. We need to think a bit about the way to implement it.

It could be relevant to be able to filter RDS instances by :

- RDS engines (e.g `PostgreSQL`, `MySQL`..)
- AWS tags (Environment=production), support of regexp could be interesting

RDS instances can have up to 50 tags, which could be a lot to ingest in Prometheus and probably not be used for alerting or visualization.

1. Can you provide more details about your ideal instance filters?
2. Can share your use case to collect AWS RDS tags in Prometheus?

Thanks,

**Comment by NikitaGl** [comment]
Great question.
Indeed, we could use some basic filtering based on resource type, but our infrastructure in used across several teams. Each team is responsible for it's resources, so we consider that in our AWS tags. Usually, all our resources has this number of tags: Name, Env, Team, Component_type, Service, Created_by. These tags are used to filter data in our Grafana.

Speacing about possible cardinality issue, indeed this might be a problem, considering quotas for ResourceTaggingAPI. I might suggest to solve this in similar way as it done in [YACE](https://github.com/nerdswords/yet-another-cloudwatch-exporter/tree/master). It also offers exporting AWS tags, but you need to explicitly specify exact tag keys you need to fetch, avoiding unwanted label overflow.

**Comment by vmercierfr** [comment]
I'm proposing to add `rds_instance_tags` metric in https://github.com/qonto/prometheus-rds-exporter/pull/72. It's very similar to [YACE](https://github.com/nerdswords/yet-another-cloudwatch-exporter/tree/master):

```
rds_instance_tags{aws_account_id="<account_id>",aws_region="<aws_region>",dbidentifier="<rds_identifier>",tag_Tag1="value1",tag_Tag2="value2"} 0
```

So you use it to filter metrics based on tags:

```
rds_instance_info + on (aws_account_id, aws_region, dbidentifier) group_left(tag_Environment) rds_instance_tags{tag_Owner="accountant"}
```

Does it meet your use case?

**Comment by NikitaGl** [comment]
🤔
It seems like. I was not using joins in promql previously, but according to docs I've read, seems totally legit, so why not 👍

**Comment by vmercierfr** [comment]
Hello,

Sorry for the late response. We had to release version 0.5.1 to fix unsupported characters in Prometheus labels, but we introduced the `aws_instance_tags` metric in [version 0.5.0](https://github.com/qonto/prometheus-rds-exporter/releases/tag/0.5.0).

Using PromQL joins, you can filter metrics based on AWS RDS instance tags.

Please upgrade your deployment to the latest version (currently `0.5.1`), and feel free to reopen this issue if something is missing.
