### ISSUE TITLE
Missing  prometheus-rds-exporter.yaml location flag on the /etc/systemd/system/prometheus-rds-exporter.service file

### ISSUE THREAD

**Issue by eranmos** [qonto/prometheus-rds-exporter#39]
**Describe the bug**
Missing  prometheus-rds-exporter.yaml location flag on the /etc/systemd/system/prometheus-rds-exporter.service file

Hi team, When installing the exporter on the Linux server I can see that you are missing a parameter that will point the service to the config file. I can't find the flag for the  prometheus-rds-exporter.yaml location

[Unit]
Description=Prometheus RDS exporter
After=network-online.target
Documentation=https://github.com/qonto/prometheus-rds-exporter

[Service]
Restart=on-failure
User=prometheus-rds-exporter
Group=prometheus-rds-exporter
Type=simple
**ExecStart=/usr/bin/prometheus-rds-exporter**
TimeoutStopSec=20s

[Install]
WantedBy=multi-user.target
~

**Desktop (please complete the following information):**

 - OS: [e.g. Linux]
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

 - Prometheus RDS exporter's version [e.g. 1.1]
 - 
 - RDS engine: [e.g. PostgreSQL]

**To Reproduce**
I stall the dpkg -i prometheus-rds-exporter_0.3.0_amd64.deb PKG and follow your instructions the readme file to configure the  prometheus-rds-exporter.yaml  file

Steps to reproduce the behavior

**Expected behavior**

**Additional context**

**Comment by vmercierfr** [comment]
Hello,

Thanks for reaching us.

The exporter is designed to work out of the box with its default parameters. The configuration file is optional and allows feature configurations.

The exporter uses the following [configuration parameters priorities](https://github.com/qonto/prometheus-rds-exporter/tree/8a6e65ea91822d9ea563207f14d963390a7f1833#configuration):

1. $HOME/prometheus-rds-exporter.yaml file
2. prometheus-rds-exporter.yaml file
3. Environment variables
4. Command line flags

In [Installation instructions](https://github.com/qonto/prometheus-rds-exporter/tree/8a6e65ea91822d9ea563207f14d963390a7f1833#debianubuntu-on-aws-ec2), we mentioned that you can optionally copy configuration template from `/usr/share/prometheus-rds-exporter/prometheus-rds-exporter.yaml.sample` to customize it.

You may change the `ExecStart` command in `/etc/systemd/system/prometheus-rds-exporter.service` like 

```bash
ExecStart=prometheus-rds-exporter --config <your_custom_configuration_file>.yaml
```

But it could be replaced during package upgrades.

Only `/usr/share/prometheus-rds-exporter/prometheus-rds-exporter.yaml.sample` is part of the Debian package. So It allows you to manage the configuration file with an automated system like Ansible.

```bash
# dpkg -S prometheus-rds-exporter
prometheus-rds-exporter: /usr/bin/prometheus-rds-exporter
prometheus-rds-exporter: /usr/share/prometheus-rds-exporter
prometheus-rds-exporter: /etc/systemd/system/prometheus-rds-exporter.service
prometheus-rds-exporter: /usr/share/prometheus-rds-exporter/prometheus-rds-exporter.yaml.sample
```

Is there a specific reason to specify the configuration file in `/etc/systemd/system/prometheus-rds-exporter.service`?

**Comment by eranmos** [comment]
Hi @vmercierfr , Thank you very much for your detailed answer.
I didn't use the Debian package installation. I created an Ansible role to install the exporter with Binary.

The issue resolved so I am closing the issue. Thanks again :-)
